esphome:
  name: espsense
  platform: ESP8266
  board: nodemcu
    

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: on

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${plug_name} Fallback Hotspot"
    password: !secret ap_pass

captive_portal:
  
# Enable logging
logger:
  level: DEBUG

ota:
  safe_mode: True
  password: "ota_safe_pass"

# Template sensor, random values published by the below time component as an example
sensor:
  - platform: template
    name: Test Sensor
    id: test_sensor
    unit_of_measurement: W


time:
  - platform: sntp
    id: sntp_time
    on_time:
          # Every 5 sec
          - seconds: /5
            then:
              # Change the sensor value randomly every 5 seconds
              # !!!!! Don't actually use this! For demo purposes only !!!!!
              - lambda: !lambda |-
                  long randomPowerState = random(5, 15);
                  id(test_sensor).publish_state((float)randomPowerState);


external_components:
  # Pull the esphome component in from this GitHub repo
  - source: github://cbpowell/ESPSense
    components: [ espsense ]

espsense:
  # You can define up to 10 "plugs" to report to Sense
  # Power value can come from any of the following:
  #   * A power sensor (in Watts)
  #   * Calculated from a current sensor (in Amps) and a voltage sensor (in Volts)
  #   * Calculated from a current sensor (in Amps) and a fixed voltage value
  plugs:
    - name: espsense
      power_sensor: test_sensor
      # current_sensor: some_current_sensor
      # voltage_sensor: some_voltage_sensor
      # voltage: 120.0
      # encrypt: false
      # mac_address: 35:4B:91:A1:FE:CC
